### ISSUE TITLE
Cannot access private property Auth_OpenID_CheckIDRequest::$identity

### ISSUE THREAD

**Issue by filips123** [openid/php-openid#146]
I tried to login with an example 'consumer' ([https://github.com/openid/php-openid/tree/master/examples/consumer](https://github.com/openid/php-openid/tree/master/examples/consumer)) to identy URL "http://_myserver.com_/server/server.php/idpage?user=USERNAME". I get an error

> **Fatal error**:  Uncaught Error: Cannot access private property Auth_OpenID_CheckIDRequest::$identity in /home/user/openid/examples/server/lib/actions.php:48
> Stack trace:
> #0 /home/user/openid/examples/server/server.php(28): action_default()
> #1 {main}
>   thrown in **/home/user/openid/examples/server/lib/actions.php** on line **48**

**Comment by adymorz** [comment]
# Summary

I got the same error on my installation.

I am using `SimpleSAMLphp` Version 1.15.0, installed using composer. It loaded `openid/php-openid` Version 2.3.0.

# Analysis

The problem is the following code in function `processRequest` in `modules/openidProvider/lib/Server.php`, which tries to acces the private property `identity` on an instance of `Auth_OpenID_CheckIDRequest`:

```
		if (!$request->idSelect() && $identity !== $request->identity) {
			/* The identity in the request doesn't match the one of the logged in user. */
			throw new SimpleSAML_Error_Exception('Logged in as different user than the one requested.');
		}
```

# Quickfix

Replace the code in `modules/openidProvider/lib/Server.php`:


```
		if (!$request->idSelect() && $identity !== $request->identity) {
```
with
```
		if (!$request->idSelect() && $identity !== $request->getIdentity()) {
```

Add the following code in class `Auth_OpenID_CheckIDRequest` in `vendor/openid/php-openid/Auth/OpenID/Server.php`:

```
    /**
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }
```

**Comment by pfefferle** [comment]
please use the latest version of the plugin, I fixed it immediately

**Comment by adymorz** [comment]
This issue has been introduced in #136

**Comment by adymorz** [comment]
Thank you!
