### ISSUE TITLE
invalid information in readme.md file

### ISSUE THREAD

**Issue by coder0107git** [openid/php-openid#163]
When I click the link [http://www.openidenabled.com/](http://www.openidenabled.com/) in the readme.md file the page there is a banner on the page says "Interested in openidenabled.com? Our Domain Broker Service may be able to get it for you. Find out how." When I click on the banner it takes me to godaddy.com.

**Comment by Lagg** [comment]
Confirming unrenewed domain. I hope this lib is still the best implementation for raw PHP OpenID :(

**Edit:** Awww man you guys went and noped out on us D: - Well that's alright it turns out people aren't trying so hard to use the more ridiculous features of openid these days so the other libs work fine. Please do remove the now-parked domain from the README eventually though.

**Comment by 7usr7local** [comment]
Same here: https://openid.net/developers/libraries/obsolete/#php

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
